### PR TITLE
Specialized implementation of WorkflowItemInput

### PR DESCRIPTION
**Pull request by omanikhi**
This specialized implementation of the WorkflowItemInput is used in release/status responses

### CODE REVIEW

**Comment by takesson** [comment]
We are so far following the principle that each module contains it own specialized implementations of this interface. 
 - I suggest placing this in cms-publish-rest with the name PublishStatusItemInput.
 - Is the configname field really necessary? ~~It ends up on a different level in the JSON compared to the proper PublishJob instances.~~ The request to the getStatus(..) method contains the configname as parameter so all the items in the response should apply to that same configname / publication name.

**Review by takesson — CHANGES_REQUESTED** [review]
See comment in PR.

**Comment by takesson** [comment]
Strike one sentence in comment above.

**Comment by omanikhi** [comment]
Moved and renamed to cms-publish-rest/src/main/java/se/simonsoft/cms/publish/rest/PublishStatusItemInput.java

**Pull request closed without merging**
